name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Start CI run
        run: 'bunx nx-cloud start-ci-run --distribute-on="8 linux-medium-js"'
